window.EONAL_SUPABASE_URL = 'NEXT_PUBLIC_SUPABASE_URL=https://yjuaiuswujqatdxeafvl.supabase.co
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_0148lTaorui5RJa03cDP2w_hVYo6vMj';
window.EONAL_SUPABASE_ANON_KEY = 'sb_publishable_0148lTaorui5RJa03cDP2w_hVYo6vMj';
